DESC user_tables;

SELECT table_name, user_stats FROM USER_TABLES;
SHOW USER;

DESC ALL_TABLES;

SELECT owner, table_name FROM ALL_TABLES WHERE owner = 'HR' ORDER BY 2;

SELECT * FROM HR.job_history;
SELECT * FROM HR.DEPARTMENTS;

CREATE USER DBA_Sonu IDENTIFIED BY sonu;

GRANT CONNECT,RESOURCE,DBA TO DBA_Sonu;

SELECT EMPLOYEE_ID, TO_DATE(END_DATE,'DD.MM.YYYY') - TO_DATE(START_DATE,'DD.MM.YYYY') AS EXPERIANCE FROM HR.JOB_HISTORY;

SELECT * FROM HR.JOBS;
SELECT * FROM HR.JOB_HISTORY;   


