DESC DBA_DATA_FILES;

SELECT * FROM DBA_DATA_FILES;

SELECT TABLESPACE_NAME, FILE_NAME, bytes/1024/1024 AS  "Size", maxbytes/1024/1024 AS "Max Size" FROM dba_data_files;

DESC DBA_FREE_SPACE;

SELECT * FROM DBA_FREE_SPACE;

ALTER DATABASE DATAFILE 'C:\APP\TBSP_DEMO\REBEL1.DBF' RESIZE 10M ;

CREATE TABLE student ( ID  NUMBER(9), NAME VARCHAR2(30)) tablespace tbsp;



BEGIN
FOR i IN 1..1000000 
LOOP
    INSERT INTO student VALUES (I,'SONUMONU');
END LOOP;
COMMIT;
END;
/

SELECT * FROM SYSTEM.STUDENT;

ALTER TABLESPACE REBELLIONRIDER  DROP DATAFILE 'C:\APP\TBSP_DEMO\REBEL3.DBF' ;

SELECT TABLESPACE_NAME, BYTES/1024/1024 FROM DBA_FREE_SPACE WHERE TABLESPACE_NAME = TBSP';


drop table system.student;

DROP TABLESPACE REBELLIONRIDER INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE REBELLIONRIDER2;

SELECT TABLESPACE_NAME FROM dba_data_files;

CREATE TABLESPACE tbsp DATAFILE 'C:\APP\TBSP_DEMO\datafile01.dbf' SIZE 1M AUTOEXTEND ON; 

DROP TABLESPACE tbsp INCLUDING CONTENTS AND DATAFILES;


CREATE TABLESPACE tbsp DATAFILE 'C:\APP\TBSP_DEMO\datafile01.dbf' SIZE 1M AUTOEXTEND ON NEXT 512K MAXSIZE 50M;

SELECT * FROM dba_data_files;

ALTER TABLESPACE tbsp OFFLINE

ALTER DATABASE RENAME FILE 'c:\app\tbsp_demo\datafile01.dbf' TO 'C:\APP\TBSP_DEMO\DATAFILE02.DBF';

ALTER TABLESPACE tbsp ONLINE;
















