CREATE USER monu IDENTIFIED BY sonu
DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp
QUOTA 20M ON users
PASSWORD expire
ACCOUNT UnLOCK;
ALTER USER sonu
ACCOUNT unlock;

SELECT name FROM V$TABLESPACE;
SELECT * FROM DBA_USERS WHERE username = 'SONU';
GRANT create session TO sonu;
GRANT RESTRICTED SESSION TO sonu;

GRANT create TO sonu;


DROP USER sonu CASCADE;
ALTER SYSTEM enable RESTRICTED SESSION;
SELECT sid,serial# FROM v$session WHERE username='SONU';
ALTER SYSTEM KILL SESSION '203,9845';
drop user mONU cascade;
