-- DATA PUMP
--** FULL EXPORT
--STEP 1 CREATE DIRECTORY OBJECT
CREATE DIRECTORY full_export AS 'F:\Data Pump\Full Export';
--2 GRANT READ WRITE PERMISSION ON DIRECTORY TO USER WHO WANT TO PERFORM DATA PUMP EXPORT
GRANT read,write ON DIRECTORY full_export TO HR;
--3 GRANT ROLE DATAPUMP_EXP_FULL_DATABASE TO HR USER IN ORDER TO PERFROME DATAPUMP EXPORT
GRANT datapump_exp_full_database TO HR;
--4 NOW COME OUT TO THE DATABASE ON RUN COMMAND LINE EXPDP UTILITE
expdp hr/hr@orcl DIRECTORY = full_export DUMPFILE = full_export.dmp LOGFILE = full_export_log.log FULL = YES;

--** EXPORTING TABLESPACES
-- STEP 1 CREATE DIRETORY
CREATE DIRECTORY tablespace_export AS 'F:/Data Pump/Tablespace Export';
--2 GRANT READ WRITE PERMISSION ON DIRECTORY TO USER WHO WANT TO PERFORM DATA PUMP EXPORT
GRANT read,write ON DIRECTORY tablespace_export TO HR;
--4 NOW COME OUT TO THE DATABASE ON RUN COMMAND LINE EXPDP UTILITE
expdp hr/hr@orcl DIRECTORY = tablespace_export DUMPFILE = tablespace_export.dmp 
LOGFILE = tblsp_export_log.log TABLESPACES = USER,EXAMPLE;


--** EXPORTING SCHEMAS
-- STEP 1 CREATE DIRETORY
CREATE DIRECTORY schemas_export AS 'F:/Data Pump/Tablespace Export';
--2 GRANT READ WRITE PERMISSION ON DIRECTORY TO USER WHO WANT TO PERFORM DATA PUMP EXPORT
GRANT read,write ON DIRECTORY schemas_export TO HR;
--4 NOW COME OUT TO THE DATABASE ON RUN COMMAND LINE EXPDP UTILITE
expdp hr/hr@orcl DIRECTORY = schema_export DUMPFILE = schema_export.dmp 
LOGFILE = schema.log SCHEMAS = HR,SCOTT;


-- EXPORTING TABLE USING PARAMETER FILES

-- STEP 1 CREATE DIRETORY
CREATE DIRECTORY schemas_export AS 'F:/Data Pump/Table Export';
--2 GRANT READ WRITE PERMISSION ON DIRECTORY TO USER WHO WANT TO PERFORM DATA PUMP EXPORT
GRANT read,write ON DIRECTORY Table_Export TO HR;
--3 CREATE PARAMETER FILE WITH .PAR EXTENSTION TYPE FOLLOWING CONTENT IN IT.
-- DIRECTORY = Table_Export
-- DUMPFILE  = Table_Export.dmp
-- LOGFILE   = Table_Export.log
-- TABLES    = EMPLOYEES,DEPARTMENTS
-- SAVE IT TO ANY LOCATION LIKE 'F:\TABLE_EXPORT.PAR'
--4 NOW COME OUT TO THE DATABASE ON RUN COMMAND LINE EXPDP UTILITE
expdp hr/hr@orcl PARFILE = 'F:\TABLE_EXPORT.PAR'















