CREATE GLOBAL TEMPORARY TABLE ROLL_UP
(
    YEAR NUMBER ,
    MONTH VARCHAR2(30),
    COUNTER NUMBER)
    ON COMMIT PRESERVE ROWS;
    DESCRIBE ROLL_uP;
    
     show autocommit;
     rollback;     
     set autocommit OFF;
     
     
     CREATE TABLE STUDENT ( NAME VARCHAR2(20), ROLLNO NUMBER);
     INSERT INTO STUDENT VALUES('SONU',1);
     SAVEPOINT A;
     INSERT INTO STUDENT VALUES('ANITA',2);
     SAVEPOINT B;
     SELECT * FROM STUDENT;
     SET AUTOCOMMIT OFF;
     
   ALTER TABLE STUDENT ADD ( DEPT VARCHAR2(20) );
   DESC STUDENT;
   DELETE FROM STUDENT;
   INSERT INTO STUDENT VALUES ('&NAME',&ROLLNO,'&DEPT');
   
   CREATE TABLE STUDENT_TEST 
   (
     NAME VARCHAR2(20),
     ROLLNO NUMBER,
     DEPT VARCHAR2(20)
   );
   SELECT * FROM STUDENT;
   
   INSERT ALL 
   INTO STUDENT_TEST (NAME, ROLLNO, DEPT)
   VALUES(NAME,5,DEPT)
   INTO STUDENT_TEST (NAME,ROLLNO, DEPT)
   VALUES(NAME, ROLLNO,'ARTS')
   SELECT NAME,ROLLNO,DEPT FROM STUDENT WHERE DEPT = 'COMP SCIE';
   
   
   
   SELECT * FROM STUDENT_TEST;
   
   
   
   
   
    