CREATE TABLE STUDENT 
(
   FName VARCHAR2(20) NOT NULL,
   LName VARCHAR2(20) NOT NULL,
   Rollno NUMBER NOT NULL,
   Dept VARCHAR2(20)
   );
   SELECT * FROM STUDENT;
   INSERT INTO STUDENT VALUES('&FNAME','&LNAME',&ROLLNO,'&DEPT');
   