select tablespace_name , contents from USER_TABLESPACES;
select * from user_users;
select * from USER_TS_QUOTAS;

SELECT SPACE FROM RECYCLEBIN WHERE TS_NAME = 'USERS';
ALTER TABLESPACE USERS READ ONLY;
SELECT STATUS FROM USER_TABLESPACES WHERE TABLESPACE_NAME ='USERS';
ALTER TABLESPACE USERS READ WRITE;
SELECT STATUS  FROM USER_TABLESPACES WHERE TABLESPACE_NAME = 'USERS';