create user U_SONU IDENTIFIED BY SONUMONU
DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp
QUOTA unlimited ON users 

PASSWORD expire
ACCOUNT unlock;

grant exp_full_database  to u_sonu;


drop user u_sonu cascade;
create profile LIMITED_PROFILE limit FAILED_LOGIN_ATTEMPTS 5;
alter profile LIMITED_PROFILE limit PASSWORD_REUSE_MAX 1 PASSWORD_REUSE_TIME UNLIMITED;
alter user U_sonu identified by shaikh;
drop user U_sonu cascade;
drop profile LIMITED_PROFILE;
GRANT CREATE table TO U_SONU;


drop user u_sonu;
alter system enable RESTRICTED SESSION;
SELECT  SID,SERIAL# FROM V$SESSION WHERE USERNAME = 'U_SONU';
ALTER SYSTEM KILL SESSION '37,255';
DROP USER U_SONU CASCADE;
ALTER SYSTEM DISABLE RESTRICTED SESSION;


GRANT RESOURCE TO HR;
GRANT DBA TO HR;


CREATE USER SONUMONU IDENTIFIED BY HAAA;
DROP USER SONUMONU;
CREATE USER SONUMONU IDENTIFIED BY SHAIKH;
CREATE ROLE SONUROLE ;
GRANT CREATE SESSION TO SONUMONU;

GRANT CREATE SESSION, CREATE TABLE TO SONUROLE;
ALTER USER SONUMONU DEFAULT ROLE SONUROLE;
SET ROLE SONUROLE;

ALTER ROLE SONUROLE IDENTIFIED BY SONU;
GRANT SONUROLE TO SONUMONU;
REVOKE SONUROLE FROM SONUMONU;
SET ROLE NONE;

SET ROLE SONUROLE IDENTIFIED BY SONU;

select tablespace_name, contents from USER_TABLESPACES;
DROP TABLESPACE SONUSHAIKH_TEMP2;













