-- TABLE SPACES IN ORACLE --
-- creating a permanet table space with small file tablespaces
CREATE SMALLFILE TABLESPACE programmerneverdie
DATAFILE
   'C:\Users\sonu\SQL DEV\TBSP\datafile1.dbf' SIZE 20M,
   'C:\Users\sonu\SQL DEV\TBSP\datafile2.dbf'SIZE 20M
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

-- Creating a perment table space with big file table spaces
CREATE BIGFILE TABLESPACE programmerneverdie2
DATAFILE
   'C:\Users\sonu\SQL DEV\TBSP\big_datafile.bdf' SIZE 1G
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;


-- CREATING A TEMPORARY TABLE SPACES 
CREATE SMALLFILE TEMPORARY TABLESPACE programmerneverdie_temp
TEMPFILE
   'C:\Users\sonu\SQL DEV\TBSP\temp_datafile1.dbf' SIZE 20M,
   'C:\Users\sonu\SQL DEV\TBSP\temp_datafile2.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

-- CREATE A TEMPORARY TABLE SPACE WITH BIG FILE
CREATE BIGFILE TEMPORARY TABLESPACE programmerneverdie_big_temp
TEMPFILE
 'C:\Users\sonu\SQL DEV\TBSP\bigfile_temp_datafile.dbf' SIZE 1G
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 100M;

-- CREATE UNDO TABLESPACE WITH SMALLFILE
CREATE SMALLFILE UNDO TABLESPACE tbsp_undo
DATAFILE
   'C:\Users\sonu\SQL DEV\TBSP\tbsp_undo.bdf' SIZE 100M
AUTOEXTEND ON NEXT 500M
MAXSIZE UNLIMITED
RETENTION NOGUARANTEE;