--MATERIALIZED VIEW
-- MATERIALIZED VIEW WITH COMPLETE OPTION 

CREATE MATERIALIZED VIEW mvw_emp
BUILD IMMEDIATE
REFRESH FORCE
ON COMMIT
AS
SELECT employee_id, first_name,last_name FROM HR.EMPLOYEES;

-- MATERIALIZED VIEW ON DEMAND OPTION
CREATE MATERIALIZED VIEW mvw_emp2
BUILD IMMEDIATE
REFRESH FORCE
ON DEMAND
AS
SELECT employee_id, first_name,last_name,HIRE_DATE FROM HR.EMPLOYEES;

SELECT * FROM mvw_emp2; 


INSERT INTO HR.EMPLOYEES (employee_Id,last_name,email,hire_date,job_Id) VALUES(300,'sonu','sonu123', TO_DATE('12-JUN-20','DD-MON-YY'),'AD_PRES');

EXECUTE DBMS_MVIEW.REFRESH('mvw_emp2');

-- MATERIALIZED VIEW WITH REFRESH FAST CAUSE
--STEP 1 CREATE MATERIALIZED VIEW LOG ON TARGET TABLE

CREATE MATERIALIZED VIEW LOG ON HR.EMPLOYEES
WITH PRIMARY KEY
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON HR.EMPLOYEES;

CREATE MATERIALIZED VIEW mvw_emp3
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND
AS
SELECT employee_id, first_name, last_name FROM HR.EMPLOYEES;

SELECT * FROM mvw_emp2;

