-- RECOVERY CATALOG
SHOW USER;
-- Create table space
CREATE TABLESPACE recovery_catalog
DATAFILE
    'C:\app\RCATLOG\RC01.DBF' SIZE 50M;
    
  -- CREAT USER TO HAND
  CREATE USER RMAN_USER IDENTIFIED BY RMAN
  DEFAULT TABLESPACE recovery_catalog
  QUOTA UNLIMITED ON recovery_catalog;
  
  -- grant the permissiong
  
  GRANT CONNECT,RESOURCE, RECOVERY_CATALOG_OWNER TO RMAN_USER;
  
  -- CONNECT TO RMAN
  --RMAN> CONNECT CATALOG RMAN_USER/RMAN;
  