-- ** Oracle User Management***
-- CREATE USER

CREATE USER user1 IDENTIFIED BY sonu
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 50M ON users
PASSWORD EXPIRE
ACCOUNT UNLOCK;

-- User data dictionary
SELECT * FROM DBA_USERS;
SELECT username,user_id,default_tablespace,temporary_tablespace, account_status,profile FROM DBA_USERS WHERE username = 'USER1';

-- GRANT CREATE SESSION PRIVEGE TO USER
GRANT CREATE SESSION TO user1;

-- CHANGE DEFAULT TABLESPACE
SELECT * FROM DBA_TABLESPACES;

ALTER USER user1 DEFAULT TABLESPACE tbsp QUOTA 2M ON tbsp;

-- LOCK & UNCLOCK PROFILE

ALTER USER user1 ACCOUNT LOCK;

ALTER USER user1 ACCOUNT UNLOCK;

-- CHANGE PASSWORD

ALTER USER user1 IDENTIFIED BY sonu PASSWORD EXPIRE;

-- DROP USER
DROP USER user1 CASCADE;


-- CREATE USER WITH ALL DEFAULT OPTION
CREATE USER superman IDENTIFIED BY superman;
CREATE USER hulk IDENTIFIED BY hulk;

--** Previlege Management**
-- SHOW THE PRIVILEGE
SELECT * FROM SESSION_PRIVS ORDER BY 1;
-- SYSTEM Privilege

GRANT CREATE TABLE, CREATE SESSION TO hulk, superman;

-- WITH ADMIN OPTION
GRANT CREATE TABLESPACE TO hulk,superman WITH ADMIN OPTION;

GRANT SELECT ANY TABLE TO hulk,superman;

-- Object Privilege

GRANT ALL ON HR.employees TO hulk,superman;

GRANT CREATE ANY  TABLE TO hulk ;

GRANT SELECT ON hr.EMPLOYEES TO hulk WITH GRANT OPTION;

-- ROLES:

-- CREATE ROLE
-- NOT IDENTIFIED CLAUSE
CREATE ROLE operation NOT IDENTIFIED;

-- IDENTIFIED BY password CLAUSE
CREATE ROLE operation2 IDENTIFIED BY sonu;

--IDENTIFIED BY EXTERNALLY claus 

CREATE ROLE operation3 IDENTIFIED BY EXTERNALLY;

--IDENTIFIED BY GLOBALLY CLAUSE
CREATE ROLE operation4 IDENTIFIED BY GLOBALLY;


--GRANT SYSTEM PRIVILEGE TO ROLES
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER, CREATE PROCEDURE TO operation WITH ADMIN OPTION;

-- GRANT OBJECT PRIVILEGE TO ROLES

GRANT SELECT, UPDATE, DELETE ON HR.employees TO operation;

--GRANT ROLE TO ANOTHER ROLE

GRANT operation to operation2;

-- VIEWING THE ROLSE ASSIGE TO USER USERS

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE IN ('HR' ,'HULK','SUPERMAN','SYSTEM') ORDER BY 1;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'HULK';

-- GRANT ROLES TO USERS

GRANT operation TO HULK WITH ADMIN OPTION;


--  *****USER PROFILE****
-- DATA DICTIONARY FOR PROFILE

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

-- CREATE PROFILE
CREATE PROFILE DW_Profile LIMIT
SESSIONS_PER_USER 2
IDLE_TIME 5
CONNECT_TIME 10;

-- ASSIGNED PROFILE TO USERS
ALTER USER HULK PROFILE DW_Profile;

CREATE USER RAJ IDENTIFIED BY RAJ PROFILE DW_Profile;

SELECT * FROM DBA_USERS WHERE USERNAME = 'HULK';
