SET SERVEROUTPUT ON;
-- EXCEPTION HANDLING IN 
--USER DEFINE EXCEPTION USING EXCEPTION VARIABLE
DECLARE
    var_devident NUMBER := 24;
    var_devisor  NUMBER := 0;
    var_result NUMBER;
    ex_ZeroDev EXCEPTION;
BEGIN
    IF var_devisor = 0 THEN
        RAISE ex_ZeroDev;
    END IF;
    var_result := var_devident / var_devisor;
    DBMS_OUTPUT.PUT_LINE('Result: '||var_result);
EXCEPTION
    WHEN ex_ZeroDev THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: YOUR DEVISOR IS ZERO.');
END;
/

--RAISE APPLICATION ERROR
ACCEPT age NUMBER PROMPT 'WHAT IS YOUR AGE?';
DECLARE
    var_age NUMBER := &age;
BEGIN
    IF var_age < 18 THEN
        RAISE_APPLICATION_ERROR(-20008,'YOUR ARE TOO YOUNG FOR DRINKS');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('HELLO, WHAT WOULD YOU LIKE TO HAVE?');
    
    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

-- EXAMPLE
CREATE OR REPLACE PROCEDURE proc_timesheet(tDay DATE) IS
BEGIN
    IF TO_CHAR(tDay,'DY') IN ('SAT','SUN') THEN
        RAISE_APPLICATION_ERROR(-20001,'YOU CAN NOT FILL TIMESHEET FOR WEEKEND DAYS');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('TIME SHEET FILED FOR '||TO_CHAR(tDay,'DAY'));
    
    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE);
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        
END proc_timesheet;
/
EXECUTE prOc_timesheet(SYSDATE + 2);
/*
SELECT * FROM DBA_OBJECTS;
SELECT OWNER,OBJECT_NAME FROM DBA_OBJECTS WHERE object_type = 'TABLE' AND OWNER = 'SYSTEM';
SELECT * FROM SCHEMA_AUDIT;
DESCRIBE USER_OBJECTS;
SELECT * FROM USER_OBJECTS;
*/

-- PREGMA EXCEPTION ERROR
ACCEPT v_age NUMBER PROMPT 'WHAT IS YOUR AGE BRO ?';
DECLARE
    ex_age EXCEPTION;
    v_age NUMBER;
    PRAGMA EXCEPTION_INIT(ex_age,-20008);
BEGIN
    IF v_age < 18 THEN
        RAISE_APPLICATION_ERROR(-20008,'YOUR ARE TOO YOUNG FOR DRINKS');
    END IF;
    
   DBMS_OUTPUT.PUT_LINE('`HELLO WHAT WOULD YOU LIKE TO HAVE`');
    
    EXCEPTION WHEN ex_age THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/





