-- *** STORE PROCEDURE ***
-- PROCEDURE WITHOUT PARAMETER

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE pr_sonu IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO THIS IS THE NOREMAL PROCEDURE');
END pr_sonu;
/

--- PARAMETERIZED STORED PROCEDURE
CREATE OR REPLACE PROCEDURE pr_salaryhike(empid NUMBER,salraise NUMBER) 
IS
BEGIN
    UPDATE EMPLOYEES SET SALARY = SALARY + (SALARY * 5) / 100 WHERE EMPLOYEE_ID = empid;
END;
/

EXECUTE pr_salaryhike(100,10);
SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;

SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT SALARY FROM EMPLOYEES WHERE ROWNUM = 1 ORDER BY SALARY DESC ;

SELECT FIRST_NAME,SALARY FROM(
    SELECT FIRST_NAME,SALARY, RANK() OVER( ORDER BY SALARY DESC) RANKER FROM EMPLOYEES)
    WHERE RANKER = 3;
    
-- PROCEDURE TO FIND 3RD HIGHEST PAID EMPLOYEE
CREATE OR REPLACE PROCEDURE pr_highestpaid(salRank NUMBER)
IS
    salaryRank NUMBER := salRank;
BEGIN
    SELECT FIRST_NAME,SALARY,JOB_ID FROM (
        SELECT FIRST_NAME,SALARY,JOB_ID, RANK() OVER (ORDER BY SALARY DESC) RANKER FROM EMPLOYEES)
        WHERE RANKER = salaryRank;
END;
/


















